export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';


export const ADD_ITEM_TO_CHATBOT_CART = 'ADD_ITEM_TO_CHATBOT_CART';
export const REMOVE_ITEM_FROM_CHATBOT_CART = 'REMOVE_ITEM_FROM_CHATBOT_CART';
export const CLEAR_CHATBOT_CART = 'CLEAR_CHATBOT_CART';

