export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';


// export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
// export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
// export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

// export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
// export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
// export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

// export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
// export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
// export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';


// export const RESET_ERROR = 'RESET_ERROR';