export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
export const RECEIVED_MESSAGE_SUCCESS = 'RECEIVED_MESSAGE_SUCCESS';
export const SET_CHATBOT_ID = 'SET_CHATBOT_ID';
export const SET_ORDER_DEATILS = 'SET_ORDER_DEATILS';
export const CLEAR_ORDER_DEATILS = 'CLEAR_ORDER_DEATILS';

