
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const GET_ORDERS_FOR_USER_REQUEST = 'GET_ORDERS_FOR_USER_REQUEST';
export const GET_ORDERS_FOR_USER_SUCCESS = 'GET_ORDERS_FOR_USER_SUCCESS';
export const GET_ORDERS_FOR_USER_FAIL = 'GET_ORDERS_FOR_USER_FAIL';


export const CLEAR_ORDER = 'CLEAR_ORDER';