export const GET_BESTSELLERS_SUCCESS = 'GET_BESTSELLERS_SUCCESS';
export const GET_BESTSELLERS_REQUEST = 'GET_BESTSELLERS_REQUEST';
export const GET_BESTSELLERS_FAIL = 'GET_BESTSELLERS_FAIL';

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';


export const SET_SELECTED_ITEM_FOR_POPUP = 'SET_SELECTED_ITEM_FOR_POPUP';
export const REMOVE_SELECTED_ITEM_FROM_POPUP = 'REMOVE_SELECTED_ITEM_FROM_POPUP';

