export const SET_RESERVATION_DATA = 'SET_RESERVATION_DATA';
export const CLEAR_RESERVATION_DATA = 'CLEAR_RESERVATION_DATA';


export const SET_RESERVATION_DATA_FROM_CHATBOT = 'SET_RESERVATION_DATA_FROM_CHATBOT';
export const CLEAR_RESERVATION_DATA_FROM_CHATBOT = 'CLEAR_RESERVATION_DATA_FROM_CHATBOT';


export const SET_TABLE_FROM_CHATBOT = 'SET_TABLE_FROM_CHATBOT';
export const CLEAR_TABLE_FROM_CHATBOT = 'CLEAR_TABLE_FROM_CHATBOT';


export const GET_TABLES_REQUEST = 'GET_TABLES_REQUEST';
export const GET_TABLES_SUCCESS = 'GET_TABLES_SUCCESS';
export const GET_TABLES_FAIL = 'GET_TABLES_FAIL';


export const BOOK_TABLE_REQUEST = 'BOOK_TABLE_REQUEST';
export const BOOK_TABLE_SUCCESS = 'BOOK_TABLE_SUCCESS';
export const BOOK_TABLE_FAIL = 'BOOK_TABLE_FAIL';

export const GET_RESERVATIONS_FOR_USER_REQUEST = 'GET_RESERVATIONS_FOR_USER_REQUEST';
export const GET_RESERVATIONS_FOR_USER_SUCCESS = 'GET_RESERVATIONS_FOR_USER_SUCCESS';
export const GET_RESERVATIONS_FOR_USER_FAIL = 'GET_RESERVATIONS_FOR_USER_FAIL';


