export const SET_RESERVATION_DATA = 'SET_RESERVATION_DATA';
export const CLEAR_RESERVATION_DATA = 'CLEAR_RESERVATION_DATA';

export const GET_TABLES_REQUEST = 'GET_TABLES_REQUEST';
export const GET_TABLES_SUCCESS = 'GET_TABLES_SUCCESS';
export const GET_TABLES_FAIL = 'GET_TABLES_FAIL';


export const BOOK_TABLE_REQUEST = 'BOOK_TABLE_REQUEST';
export const BOOK_TABLE_SUCCESS = 'BOOK_TABLE_SUCCESS';
export const BOOK_TABLE_FAIL = 'BOOK_TABLE_FAIL';


// export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
// export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';




// export const RESET_ERROR = 'RESET_ERROR';